# Logistic Regression

## Importing the libraries

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [5]:
dataset = pd.read_csv('Breast_Cancer.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

## Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

## Training the Logistic Regression model on the Training set

In [8]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(random_state=0)
log_reg.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Making the Confusion Matrix

In [12]:
from sklearn.metrics import accuracy_score, confusion_matrix
y_pred = log_reg.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)*100

[[103   4]
 [  5  59]]


94.73684210526315

# K-Nearest Neighbors (K-NN)

## Training the K-NN model on the Training set

In [13]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
knn.fit(X_train, y_train)

KNeighborsClassifier()

## Making the Confusion Matrix

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix
y_pred = knn.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)*100

[[102   5]
 [  5  59]]


94.15204678362574

# Support Vector Machine (SVM)

## Training the SVM model on the Training set

In [15]:
from sklearn.svm import SVC
svc_cl = SVC(kernel='linear', random_state=0)
svc_cl.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

## Making the Confusion Matrix

In [17]:
from sklearn.metrics import accuracy_score, confusion_matrix
y_pred = svc_cl.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)*100

[[102   5]
 [  5  59]]


94.15204678362574

# Kernel SVM

## Training the Kernel SVM model on the Training set

In [18]:
from sklearn.svm import SVC
svc_cl = SVC(kernel='rbf', random_state=0)
svc_cl.fit(X_train, y_train)

SVC(random_state=0)

## Making the Confusion Matrix

In [19]:
from sklearn.metrics import accuracy_score, confusion_matrix
y_pred = svc_cl.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)*100

[[101   6]
 [  3  61]]


94.73684210526315

# Naive Bayes

## Training the Naive Bayes model on the Training set

In [23]:
from sklearn.naive_bayes import GaussianNB
nb_gauss = GaussianNB()
nb_gauss.fit(X_train, y_train)

GaussianNB()

## Making the Confusion Matrix

In [24]:
from sklearn.metrics import accuracy_score, confusion_matrix
y_pred = nb_gauss.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)*100

[[100   7]
 [  3  61]]


94.15204678362574

# Decision Tree Classification

## Training the Decision Tree Classification model on the Training set

In [25]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion='entropy', random_state=0)
dt.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

## Making the Confusion Matrix

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix
y_pred = dt.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)*100

[[103   4]
 [  4  60]]


95.32163742690058

# Random Forest Classification

## Training the Random Forest Classification model on the Training set

In [27]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
rf.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

## Making the Confusion Matrix

In [28]:
from sklearn.metrics import accuracy_score, confusion_matrix
y_pred = rf.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)*100

[[102   5]
 [  8  56]]


92.39766081871345