# Multiple Linear Regression

## Importing the libraries

In [78]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [79]:
dataset = pd.read_csv('PowerPlant_DataSet.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [80]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Training the Multiple Linear Regression model on the Training set

In [81]:
from sklearn.linear_model import LinearRegression
lr_reg = LinearRegression()
lr_reg.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [82]:
y_pred = lr_reg.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]


## Evaluating the Model Performance

In [83]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
print(f"r2_score of our multi_linear regressor model is: {r2_score(y_test, y_pred)}")
print(f"mean_absolute_error of our multi_linear regressor model is: {mean_absolute_error(y_test, y_pred)}")
print(f"mean_squared_error of our multi_linear regressor model is: {mean_squared_error(y_test, y_pred)}")

r2_score of our multi_linear regressor model is: 0.9325315554761303
mean_absolute_error of our multi_linear regressor model is: 3.566564655203825
mean_squared_error of our multi_linear regressor model is: 19.73369930349764


# Polynomial Regression

## Splitting the dataset into the Training set and Test set

In [84]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Training the Polynomial Regression model on the Training set

In [85]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree=4)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

LinearRegression()

## Predicting the Test set results

In [86]:
y_pred = regressor.predict(poly_reg.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[433.94 431.23]
 [457.9  460.01]
 [460.52 461.14]
 ...
 [469.53 473.26]
 [438.27 438.  ]
 [461.66 463.28]]


## Evaluating the Model Performance

In [87]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
print(f"r2_score of our multi_linear regressor model is: {r2_score(y_test, y_pred)}")
print(f"mean_absolute_error of our multi_linear regressor model is: {mean_absolute_error(y_test, y_pred)}")
print(f"mean_squared_error of our multi_linear regressor model is: {mean_squared_error(y_test, y_pred)}")

r2_score of our multi_linear regressor model is: 0.9458192606428147
mean_absolute_error of our multi_linear regressor model is: 3.1360304044631873
mean_squared_error of our multi_linear regressor model is: 15.847207180500604


# Support Vector Regression

In [88]:
y = y.reshape(len(y),1)

## Splitting the dataset into the Training set and Test set

In [89]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [90]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)

## Training the SVR model on the Training set

In [91]:
from sklearn.svm import SVR
svr_reg = SVR(kernel='rbf')
svr_reg.fit(X_train, y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

## Predicting the Test set results

In [92]:
y_pred = sc_y.inverse_transform(svr_reg.predict(sc_X.transform(X_test)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[434.05 431.23]
 [457.94 460.01]
 [461.03 461.14]
 ...
 [470.6  473.26]
 [439.42 438.  ]
 [460.92 463.28]]


## Evaluating the Model Performance

In [93]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
print(f"r2_score of our multi_linear regressor model is: {r2_score(y_test, y_pred)}")
print(f"mean_absolute_error of our multi_linear regressor model is: {mean_absolute_error(y_test, y_pred)}")
print(f"mean_squared_error of our multi_linear regressor model is: {mean_squared_error(y_test, y_pred)}")

r2_score of our multi_linear regressor model is: 0.9480784049986258
mean_absolute_error of our multi_linear regressor model is: 2.9951783924513267
mean_squared_error of our multi_linear regressor model is: 15.186434937782035


# Decision Tree Regression

## Splitting the dataset into the Training set and Test set

In [94]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Training the Decision Tree Regression model on the Training set

In [95]:
from sklearn.tree import DecisionTreeRegressor
dt_reg = DecisionTreeRegressor(random_state=0)
dt_reg.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

## Predicting the Test set results

In [96]:
y_pred = dt_reg.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[431.28 431.23]
 [459.59 460.01]
 [460.06 461.14]
 ...
 [471.46 473.26]
 [437.76 438.  ]
 [462.74 463.28]]


## Evaluating the Model Performance

In [97]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
print(f"r2_score of our multi_linear regressor model is: {r2_score(y_test, y_pred)}")
print(f"mean_absolute_error of our multi_linear regressor model is: {mean_absolute_error(y_test, y_pred)}")
print(f"mean_squared_error of our multi_linear regressor model is: {mean_squared_error(y_test, y_pred)}")

r2_score of our multi_linear regressor model is: 0.922905874177941
mean_absolute_error of our multi_linear regressor model is: 3.103923719958203
mean_squared_error of our multi_linear regressor model is: 22.549093991640547


# Random Forest Regression

## Splitting the dataset into the Training set and Test set

In [98]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Training the Random Forest Regression model on the whole dataset

In [99]:
from sklearn.ensemble import RandomForestRegressor
rf_reg = RandomForestRegressor(n_estimators=10, random_state=0)
rf_reg.fit(X_train, y_train)

<ipython-input-99-7373d233db1e>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf_reg.fit(X_train, y_train)


RandomForestRegressor(n_estimators=10, random_state=0)

## Predicting the Test set results

In [100]:
y_pred = rf_reg.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[434.05 431.23]
 [458.79 460.01]
 [463.02 461.14]
 ...
 [469.48 473.26]
 [439.57 438.  ]
 [460.38 463.28]]


## Evaluating the Model Performance

In [101]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
print(f"r2_score of our multi_linear regressor model is: {r2_score(y_test, y_pred)}")
print(f"mean_absolute_error of our multi_linear regressor model is: {mean_absolute_error(y_test, y_pred)}")
print(f"mean_squared_error of our multi_linear regressor model is: {mean_squared_error(y_test, y_pred)}")

r2_score of our multi_linear regressor model is: 0.9615908334363876
mean_absolute_error of our multi_linear regressor model is: 2.452366771159876
mean_squared_error of our multi_linear regressor model is: 11.234213991640557
